/* SPDX-License-Identifier: GPL-3.0-or-later */

public enum TokenType {
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, // ( )
    LEFT_BRACE, RIGHT_BRACE, // []

    COMMA, ASSIGNMENT, COLON, // , = :
    OCTOTHORPE, AMPERSAND, DOLLAR, // # & $
    ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION, MODULO, // + - * / %
    INCREMENT, DECREMENT, // ++ --

    GREATER, LESSER, // > <
    GREATER_EQUAL, LESSER_EQUAL, // >= <=
    EQUAL, NOT_EQUAL, // == <>

    IDENTIFIER,

    CHAR_LIT,
    INT_LIT,
    FLOAT_LIT,
    BOOL_LIT,
    STR_LIT,

    // RESERVED WORDS
    AND, OR, NOT,
    PRINT, SCAN,
    DECLARE,
    INT, BOOL, FLOAT, CHAR,
    SCRIPT, AREA, START, END,
    IF, ELSE, FOR, REPEAT, WHEN, EOL, EOF
}